#!/bin/sh
#/etc/init.d/myService
export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
start)
exec forever --sourceDir=/home/pi/ERLT_PE_DRIVER -p /home/pi/ERLT_PE_DRIVER app.js  #scriptarguments
;;
stop)
exec forever stop --sourceDir=/home/pi/ERLT_PE_DRIVER app.js
;;
*)
echo "Usage: /etc/init.d/webdriver {start|stop}"
exit 1
;;
esac
exit 0
