#!/bin/sh

#/etc/init.d/webdriver

### BEGIN INIT INFO
# Provides:       webdriver
# Required-Start:    $local_fs $remote_fs $network $syslog $named
# Required-Stop:     $local_fs $remote_fs $network $syslog $named
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: starts the PE webdriver
# Description:       starts webdriver using start-stop-daemon
### END INIT INFO

export PATH=$PATH:/usr/local/bin
export NODE_PATH=$NODE_PATH:/usr/local/lib/node_modules

case "$1" in
start)
exec forever --sourceDir=/home/pi/ERLT_PE_DRIVER -p /home/pi/ERLT_PE_DRIVER app.js  #scriptarguments
;;
stop)
exec forever stop --sourceDir=/home/pi/ERLT_PE_DRIVER app.js
;;
*)
echo "Usage: /etc/init.d/webdriver {start|stop}"
exit 1
;;
esac
exit 0
