#!/bin/bash
# /etc/init.d/webdriver

### BEGIN INIT INFO
# Provides:          webdriver
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: ERLT webdriver
# Description:       This service is used to start ERLT PE webdriver service
### END INIT INFO


case "$1" in
    start)
        echo "Starting webdriver"
        /home/pi/ERLT_PE_DRIVER/start_webdriver.sh &
        ;;
    stop)
        echo "Stopping webdriver"
        killall -9 webdriver.sh
        killall -9 node
        ;;
    *)
        echo "Usage: /etc/init.d/webdriver start|stop"
        exit 1
        ;;
esac

exit 0
